GET http://localhost:8080
###
GET http://localhost:8080/testlisting
###
GET http://localhost:8080/listings
###
GET http://localhost:8080/listings/new
###
GET http://localhost:8080/listings/6627b28acc3b07a927e20674
###
GET http://localhost:8080/randomShit
###
GET http://localhost:8080/listings/3247b28acc3b07a927e20674
###
GET http://localhost:8080/listings/cc3b07a927e20674
###
POST http://localhost:8080/listings HTTP/1.1
content-type: application/json

{
    "title": "Forrest Gugfgfmp",
    "description": "A forrest gump edition",
    "price": 44444,
    "location": "alalalal"
}