GET http://localhost:8080
###
GET http://localhost:8080/testlisting
###
GET http://localhost:8080/listings
###
GET http://localhost:8080/listings/new
###
GET http://localhost:8080/listings/6627b28acc3b07a927e20674
###
GET http://localhost:8080/randomShit
###
GET http://localhost:8080/listings/3247b28acc3b07a927e20674
###
GET http://localhost:8080/listings/cc3b07a927e20674
###
POST http://localhost:8080/listings HTTP/1.1
content-type: application/json

{
    "title": "Forrest Gugfgfmp",
    "description": "A forrest gump edition",
    "price": 44444,
    "location": "alalalal",
    "country": "jingalala land"
}
###
PUT http://localhost:8080/listings/6627b28acc3b07a927e20674 HTTP/1.1
content-type: application/json

{
    "listing":{
        "title": "update test",
        "description": "A forrest gump edition",
        "price": 44444,
        "location": "alalalal"
    }
}
###
POST http://localhost:8080/listings/6634e44eef3b737ca5ca74ba/reviews HTTP/1.1
content-type: application/json

{
    "review": {
            "rating" : 4,
            "content": "f fsdfdsfsdfds e forrest inn"
        }
}
###
GET http://localhost:8080/listings/6634e44eef3b737ca5ca74ba
###
POST http://localhost:8080/listings/6634e44eef3b737ca5ca74ba?_method=DELETE